# Generated by Django 5.2 on 2026-03-02 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_paciente_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempoRegistroClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_registro",
                    models.CharField(
                        choices=[
                            ("prontuario", "Prontuário/Evolução/Avaliação"),
                            ("burocracia", "Burocracia"),
                            ("coordenação", "Coordenação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.DateField(auto_now_add=True)),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.profissional",
                    ),
                ),
            ],
        ),
    ]
