# Generated by Django 5.0.6 on 2026-03-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_temporegistroclinico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSalas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sala', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='temporegistroclinico',
            name='tipo_registro',
            field=models.CharField(choices=[('prontuario', 'Prontuário/Evolução/Avaliação'), ('burocracia', 'Burocracia'), ('coordenacao', 'Coordenação')], max_length=20),
        ),
    ]
