# Generated by Django 5.0.6 on 2026-03-04 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_configuracaosalas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.configuracaosalas'),
        ),
    ]
