# Generated by Django 5.0.6 on 2026-03-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_agendamento_ambiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalpendente',
            name='finalidade_nf',
            field=models.CharField(blank=True, choices=[('imposto_renda', 'Imposto de Renda'), ('reembolso_plano', 'Reembolso Plano de Saúde')], max_length=20, null=True),
        ),
    ]
