# Generated by Django 5.0.6 on 2026-03-06 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_notafiscalpendente_finalidade_nf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(default='fas fa-folder', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(default='fas fa-chart-bar', max_length=50)),
                ('filtros_disponiveis', models.JSONField(default=list, help_text='\n        ["dias", "profissional", "setor", "status", "tipo_atendimento"]\n        ')),
                ('query_sql', models.TextField(blank=True)),
                ('funcao_python', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriarelatorio')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='ExecucaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametros', models.JSONField()),
                ('dados_resultado', models.JSONField(blank=True, null=True)),
                ('arquivo_exportado', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('tempo_execucao', models.FloatField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.relatorioconfig')),
            ],
            options={
                'ordering': ['-data_execucao'],
            },
        ),
    ]
