# Generated by Django 5.0.6 on 2026-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_categoriarelatorio_relatorioconfig_execucaorelatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioconfig',
            name='filtros_disponiveis',
            field=models.JSONField(blank=True, default=list, help_text='\n        ["dias", "profissional", "setor", "status", "tipo_atendimento"]\n        ', null=True),
        ),
    ]
