# Generated by Django 5.2 on 2026-03-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_alter_relatorioconfig_filtros_disponiveis"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="inicio_recorrencia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="despesa",
            name="qtd_ocorrencias",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="despesa",
            name="termino_recorrencia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="despesa",
            name="tipo_recorrencia",
            field=models.CharField(
                blank=True,
                choices=[("meses", "Por quantidade"), ("data", "Por data")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="despesa",
            name="valor_total_recorrencia",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="despesa",
            name="frequencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("semanal", "Semanal"),
                    ("quinzenal", "Quinzenal"),
                    ("mensal", "Mensal"),
                    ("bimestral", "Bimestral"),
                    ("trimestral", "Trimestral"),
                    ("semestral", "Semestral"),
                    ("anual", "Anual"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
