# Generated by Django 5.2 on 2026-03-12 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_despesa_inicio_recorrencia_despesa_qtd_ocorrencias_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despesa",
            name="categoria",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "despesa"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subgrupoconta",
            ),
        ),
    ]
